name: Build and Push to DockerHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Git fetch everything
        run: git fetch --prune --unshallow

      - name: Get Github tag
        id: meta
        run: |
          echo "tag=$(echo ${{github.ref_name}} | sed -e 's/^v//')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./ibc-tester/
          file: ./ibc-tester/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: sagaxyz/ibc-tester:${{ steps.meta.outputs.tag }}, sagaxyz/ibc-tester:latest