name: ShellCheck

on: [push]

permissions:
 contents: read
jobs:
  shellcheck:
    name: Run shfmt
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/sagaxyz/*
    steps:
      - uses: actions/checkout@v4
      - name: Install shfmt
        run: go get -u mvdan.cc/sh/cmd/shfmt
      - name: Check Shell Script Formatting
        run: find . -type f -name "*.sh" -exec shfmt -i 2 -ci -d {} +